/**
 * Module: Contact page
 * Purpose: Validate and persist project inquiries with anti-spam and WhatsApp fallback
 * Used by: TanStack route /contact
 * Dependencies: React, Turnstile widget, contact service, Supabase public insert policy, privacy-safe analytics
 * Public functions: ContactPage()
 * Side effects: Supabase insert when configured, aggregate CTA event, and WhatsApp navigation
 */
import { useState, type FormEvent } from 'react';
import { submitContact } from '../lib/contact';
import { trackEvent } from '../lib/analytics';
import { TurnstileWidget } from '../components/turnstile-widget';

export function ContactPage() { const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [captchaToken, setCaptchaToken] = useState(''); const [captchaKey, setCaptchaKey] = useState(0); async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!captchaToken) { setStatus('Selesaikan CAPTCHA terlebih dahulu.'); return; } setBusy(true); setStatus(''); const data = new FormData(event.currentTarget); if (String(data.get('website') ?? '').trim()) { setBusy(false); setStatus('Terima kasih.'); return; } try { await submitContact({ nama: String(data.get('nama') ?? ''), email: String(data.get('email') ?? ''), telepon: String(data.get('telepon') ?? ''), jenisLayanan: String(data.get('jenis_layanan') ?? ''), kebutuhan: String(data.get('kebutuhan') ?? ''), anggaran: String(data.get('anggaran') ?? ''), captchaToken }); event.currentTarget.reset(); setStatus('Terima kasih — pesanmu sudah masuk.'); } catch { setStatus('Pesan belum dapat dikirim. Coba lagi atau gunakan WhatsApp.'); } finally { setBusy(false); setCaptchaToken(''); setCaptchaKey((value) => value + 1); } } const whatsappMessage = encodeURIComponent('Halo Suprayogo, saya ingin mendiskusikan project website/aplikasi.'); return <section className="page section"><p className="eyebrow">Start a project</p><h1>Tell me what should exist next.</h1><p className="lede">Ceritakan konteks, ambisi, atau problem yang sedang kamu hadapi. Tidak harus rapi.</p><form className="form" onSubmit={handleSubmit}><input name="nama" placeholder="Nama / company" required /><input name="email" type="email" placeholder="Email" required /><input name="telepon" type="tel" placeholder="Telepon / WhatsApp" required /><select name="jenis_layanan" defaultValue="website" required><option value="website">Website</option><option value="aplikasi-web">Aplikasi web</option><option value="company-profile">Company profile</option></select><input name="anggaran" placeholder="Range budget (optional)" /><textarea name="kebutuhan" placeholder="Apa yang ingin dibangun?" required /><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{ position: 'absolute', left: '-10000px', opacity: 0 }} /><TurnstileWidget key={captchaKey} onToken={setCaptchaToken} onError={setStatus} /><button className="button primary" type="submit" disabled={busy}>{busy ? 'Mengirim…' : 'Kirim inquiry ↗'}</button>{status && <p className="status" role="status">{status}</p>}</form><div className="actions"><a className="button" href={`https://wa.me/6287852600073?text=${whatsappMessage}`} rel="noreferrer" onClick={() => trackEvent('whatsapp_click')}>WhatsApp langsung ↗</a></div></section>; }
