/**
 * Module: Portfolio pages
 * Purpose: Query/filter portfolio records and render case-study details
 * Used by: TanStack routes /portfolio and /portfolio/$slug
 * Dependencies: TanStack Query/Router, portfolio service, shared Feature component
 * Public functions: PortfolioPage(), PortfolioDetailPage()
 * Side effects: Public Supabase reads when configured
 */
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from '@tanstack/react-router';
import { Feature } from '../components/site-shell';
import { getPortfolioBySlug, listPortfolio, listPortfolioCategories, type Portfolio, type PortfolioCategory } from '../lib/portfolio';
import { useLanguage } from '../lib/language';
import { t } from '../lib/i18n';
import { trackPortfolioClick } from '../lib/analytics';

export function PortfolioPage() { const { language } = useLanguage(); const [category, setCategory] = useState<PortfolioCategory | undefined>(); const [search, setSearch] = useState(''); const categories = useQuery({ queryKey: ['portfolio-categories'], queryFn: listPortfolioCategories, staleTime: 60_000 }); const result = useQuery({ queryKey: ['portfolio', category, search], queryFn: () => listPortfolio({ category, search: search || undefined }) }); const portfolio = result.data ?? []; return <section className="page section"><div className="section-heading"><div><p className="eyebrow">{t(language, 'portfolio.eyebrow')}</p><h1>{t(language, 'portfolio.title')}</h1></div><p className="muted">{portfolio.length} {language === 'id' ? 'karya terpilih' : 'selected projects'}</p></div><div className="actions"><input aria-label={t(language, 'portfolio.search')} placeholder={t(language, 'portfolio.searchPlaceholder')} value={search} onChange={(event) => setSearch(event.target.value)} />{(categories.data ?? []).map((item) => <button className={`button ${category === item.value ? 'primary' : ''}`} key={item.label} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div>{(result.isLoading || categories.isLoading) && <p className="muted">{t(language, 'portfolio.loading')}</p>}{(result.isError || categories.isError) && <p className="muted">{t(language, 'portfolio.error')}</p>} {!result.isLoading && !result.isError && portfolio.length === 0 && <p className="muted">{t(language, 'portfolio.empty')}</p>}<div className="grid">{portfolio.map((item) => <article className="card" key={item.id}><span className="tag">{item.kategori}</span><h3>{item.judul}</h3><p className="muted">{item.ringkasan}</p><p className="tag">{(item.teknologi ?? []).join(' · ')}</p><Link className="tag" to="/portfolio/$slug" params={{ slug: item.slug }} onClick={() => void trackPortfolioClick(item.id)}>{t(language, 'common.open')}</Link></article>)}</div></section>; }
export function PortfolioDetailPage() { const { language } = useLanguage(); const { slug } = useParams({ strict: false }) as { slug?: string }; const result = useQuery({ queryKey: ['portfolio-detail', slug], queryFn: async () => getPortfolioBySlug(slug ?? '') }); const item = result.data; if (result.isLoading) return <section className="page section"><p className="muted">{t(language, 'common.loading')}</p></section>; if (result.isError) return <section className="page section"><p className="muted">{t(language, 'portfolio.error')}</p></section>; if (!item) return <section className="page section"><p className="muted">{language === 'id' ? 'Portfolio tidak ditemukan.' : 'Portfolio not found.'}</p><Link className="button" to="/portfolio">{t(language, 'portfolio.back')}</Link></section>; return <section className="page section"><p className="eyebrow">{item.kategori} · {item.durasi ?? t(language, 'portfolio.detailEyebrow')}</p><h1>{item.judul}</h1><p className="lede">{item.ringkasan}</p><div className="grid"><Feature number="01" title={language === 'id' ? 'Tujuan' : 'Goal'} text={item.tujuan ?? (language === 'id' ? 'Belum diisi.' : 'Not provided yet.')} /><Feature number="02" title={language === 'id' ? 'Tantangan' : 'Challenge'} text={item.tantangan ?? (language === 'id' ? 'Belum diisi.' : 'Not provided yet.')} /><Feature number="03" title={language === 'id' ? 'Solusi' : 'Solution'} text={item.solusi ?? (language === 'id' ? 'Belum diisi.' : 'Not provided yet.')} /></div><p className="tag">{(item.teknologi ?? []).join(' · ')}</p><div className="actions"><Link className="button primary" to="/contact">{t(language, 'portfolio.discuss')} ↗</Link>{item.url_demo && <a className="button" href={item.url_demo} rel="noreferrer">{t(language, 'portfolio.visit')} ↗</a>}<Link className="button" to="/portfolio">{t(language, 'portfolio.back')}</Link></div></section>; }
