/**
 * Module: Portfolio pages
 * Purpose: Query/filter portfolio records and render case-study details
 * Used by: TanStack routes /portfolio and /portfolio/$slug
 * Dependencies: TanStack Query/Router, portfolio service, shared Feature component
 * Public functions: PortfolioPage(), PortfolioDetailPage()
 * Side effects: Public Supabase reads when configured
 */
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from '@tanstack/react-router';
import { Feature } from '../components/site-shell';
import { getPortfolioBySlug, listPortfolio, listPortfolioCategories, type Portfolio, type PortfolioCategory } from '../lib/portfolio';

export function PortfolioPage() { const [category, setCategory] = useState<PortfolioCategory | undefined>(); const [search, setSearch] = useState(''); const categories = useQuery({ queryKey: ['portfolio-categories'], queryFn: listPortfolioCategories, staleTime: 60_000 }); const result = useQuery({ queryKey: ['portfolio', category, search], queryFn: () => listPortfolio({ category, search: search || undefined }) }); const portfolio = result.data ?? []; return <section className="page section"><div className="section-heading"><div><p className="eyebrow">Portfolio</p><h1>Work that moves the room.</h1></div><p className="muted">{portfolio.length} selected projects</p></div><div className="actions"><input aria-label="Cari portfolio" placeholder="Search title or technology" value={search} onChange={(event) => setSearch(event.target.value)} />{(categories.data ?? []).map((item) => <button className={`button ${category === item.value ? 'primary' : ''}`} key={item.label} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div>{(result.isLoading || categories.isLoading) && <p className="muted">Memuat portfolio…</p>}{(result.isError || categories.isError) && <p className="muted">Portfolio belum dapat dimuat. Periksa koneksi Supabase.</p>} {!result.isLoading && !result.isError && portfolio.length === 0 && <p className="muted">Belum ada portfolio yang dipublikasikan.</p>}<div className="grid">{portfolio.map((item) => <article className="card" key={item.id}><span className="tag">{item.kategori}</span><h3>{item.judul}</h3><p className="muted">{item.ringkasan}</p><p className="tag">{(item.teknologi ?? []).join(' · ')}</p><Link className="tag" to="/portfolio/$slug" params={{ slug: item.slug }}>Open project ↗</Link></article>)}</div></section>; }
export function PortfolioDetailPage() { const { slug } = useParams({ strict: false }) as { slug?: string }; const result = useQuery({ queryKey: ['portfolio-detail', slug], queryFn: async () => getPortfolioBySlug(slug ?? '') }); const item = result.data; if (result.isLoading) return <section className="page section"><p className="muted">Memuat detail portfolio…</p></section>; if (result.isError) return <section className="page section"><p className="muted">Detail portfolio belum dapat dimuat. Periksa koneksi Supabase.</p></section>; if (!item) return <section className="page section"><p className="muted">Portfolio tidak ditemukan.</p><Link className="button" to="/portfolio">Back to work</Link></section>; return <section className="page section"><p className="eyebrow">{item.kategori} · {item.durasi ?? 'Selected case'}</p><h1>{item.judul}</h1><p className="lede">{item.ringkasan}</p><div className="grid"><Feature number="01" title="Tujuan" text={item.tujuan ?? 'Belum diisi.'} /><Feature number="02" title="Tantangan" text={item.tantangan ?? 'Belum diisi.'} /><Feature number="03" title="Solusi" text={item.solusi ?? 'Belum diisi.'} /></div><p className="tag">{(item.teknologi ?? []).join(' · ')}</p><div className="actions"><Link className="button primary" to="/contact">Discuss a similar project ↗</Link>{item.url_demo && <a className="button" href={item.url_demo} rel="noreferrer">Visit demo ↗</a>}<Link className="button" to="/portfolio">Back to work</Link></div></section>; }
