/**
 * Module: Services page
 * Purpose: Explain service lines, four-step workflow, and common questions
 * Used by: TanStack route /services
 * Dependencies: Shared Feature component and TanStack Link
 * Public functions: ServicesPage()
 * Side effects: Client-side navigation only
 */
import { Feature } from '../components/site-shell';
import { useLanguage } from '../lib/language';

export function ServicesPage() { const { language } = useLanguage(); const id = language === 'id'; return <section className="page section"><p className="eyebrow">{id ? 'Layanan' : 'Services'}</p><h1>{id ? 'Dari ide pertama hingga pengalaman yang live.' : 'From first thought to shipped experience.'}</h1><div className="grid"><Feature number="01" title="Digital presence" text={id ? 'Website dan company profile yang punya karakter dan bekerja untuk bisnis.' : 'Websites and company profiles with character that work for the business.'} /><Feature number="02" title="Web applications" text={id ? 'Interface produk yang membuat workflow rumit terasa lebih sederhana.' : 'Product interfaces that make complex workflows feel simpler.'} /><Feature number="03" title="Design direction" text={id ? 'Sistem visual dan keputusan UX yang membuat tim bergerak lebih yakin.' : 'Visual systems and UX decisions that help teams move with confidence.'} /></div><div className="section-heading"><div><p className="eyebrow">{id ? 'Cara kerja' : 'How we work'}</p><h2>{id ? 'Empat langkah jelas.' : 'Four clear moves.'}</h2></div></div><div className="grid"><Feature number="01" title="Align" text={id ? 'Kita menyamakan konteks, tujuan, dan ukuran sukses.' : 'We align on context, goals, and measures of success.'} /><Feature number="02" title="Shape" text={id ? 'Arah visual dan struktur pengalaman dibentuk bersama.' : 'We shape the visual direction and experience structure together.'} /><Feature number="03" title="Build" text={id ? 'Produk dirakit dengan ritme review yang singkat dan konkret.' : 'We build with a short, concrete review rhythm.'} /><Feature number="04" title="Launch" text={id ? 'Kita menyiapkan handoff, QA, dan langkah setelah live.' : 'We prepare the handoff, QA, and next steps after launch.'} /></div><div className="section-heading"><div><p className="eyebrow">FAQ</p><h2>{id ? 'Pertanyaan selalu diterima.' : 'Good questions welcome.'}</h2></div></div><div className="grid"><article className="card"><h3>{id ? 'Berapa lama prosesnya?' : 'How long does it take?'}</h3><p className="muted">{id ? 'Biasanya 4–10 minggu, tergantung ruang lingkup dan kecepatan review.' : 'Usually 4–10 weeks, depending on scope and review speed.'}</p></article><article className="card"><h3>{id ? 'Apakah bisa mulai kecil?' : 'Can we start small?'}</h3><p className="muted">{id ? 'Bisa. Kita bisa mulai dari satu halaman penting atau prototype terarah.' : 'Yes. We can start with one important page or a focused prototype.'}</p></article><article className="card"><h3>{id ? 'Teknologi apa yang dipakai?' : 'What technology do you use?'}</h3><p className="muted">{id ? 'Dipilih berdasarkan kebutuhan; fondasi saat ini React/TanStack dan Supabase.' : 'Chosen for the need; the current foundation is React/TanStack and Supabase.'}</p></article></div></section>; }
