/**
 * Module: Owner admin application
 * Purpose: Authenticate owner and manage portfolio, testimonials, slides, and contact inbox
 * Used by: TanStack routes /auth/login and /admin
 * Dependencies: React, Supabase owner data service, app.css
 * Public functions: AdminApp()
 * Side effects: Auth session, database CRUD, and Storage uploads through RLS
 */
import { useEffect, useState, type FormEvent } from 'react';
import { useLocation, useNavigate } from '@tanstack/react-router';
import { createPortfolio, createTestimonial, deletePortfolio, getOwnerSession, listContactMessages, listOwnerPortfolio, listSlides, listTestimonials, signInOwner, signOutOwner, uploadSlide, type Slide, type Testimonial } from './lib/admin';
import type { Portfolio } from './lib/portfolio';
import './app.css';

type Message = { id: string; nama: string; email: string; status: string };
export function AdminApp() { const [session, setSession] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [items, setItems] = useState<Portfolio[]>([]); const [testimonials, setTestimonials] = useState<Testimonial[]>([]); const [slides, setSlides] = useState<Slide[]>([]); const [messages, setMessages] = useState<Message[]>([]); const [status, setStatus] = useState(''); const navigate = useNavigate(); const location = useLocation();
  async function load() { try { const current = await getOwnerSession(); setSession(Boolean(current.data.session)); if (current.data.session) { if (location.pathname === '/auth/login') await navigate({ to: '/admin', replace: true }); const [portfolio, social, presentation, inbox] = await Promise.all([listOwnerPortfolio(), listTestimonials(), listSlides(), listContactMessages()]); setItems(portfolio); setTestimonials(social); setSlides(presentation); setMessages(inbox as Message[]); } } catch (error) { setStatus(error instanceof Error ? error.message : 'Supabase environment belum dikonfigurasi.'); } }
  useEffect(() => { void load(); }, [location.pathname]);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus(''); try { const result = await signInOwner(email, password); if (result.error) throw result.error; await navigate({ to: '/admin', replace: true }); } catch (error) { setStatus(error instanceof Error ? error.message : 'Login gagal.'); } }
  async function addProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createPortfolio({ judul: String(form.get('judul')), slug: String(form.get('slug')), kategori: String(form.get('kategori')) as Portfolio['kategori'], ringkasan: String(form.get('ringkasan')) }); event.currentTarget.reset(); await load(); setStatus('Portfolio tersimpan.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Gagal menyimpan portfolio.'); } }
  async function removeProject(id: string) { if (!window.confirm('Sembunyikan portfolio ini dari publik?')) return; try { await deletePortfolio(id); await load(); setStatus('Portfolio disembunyikan.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Gagal mengubah portfolio.'); } }
  async function addTestimonial(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createTestimonial({ nama: String(form.get('nama')), jabatan: String(form.get('jabatan')), kutipan: String(form.get('kutipan')) }); event.currentTarget.reset(); await load(); setStatus('Testimonial tersimpan.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Gagal menyimpan testimonial.'); } }
  async function addSlide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('file'); if (!(file instanceof File) || !file.size) return setStatus('Pilih file HTML atau PDF.'); try { await uploadSlide(file, String(form.get('judul')), String(form.get('slug'))); event.currentTarget.reset(); await load(); setStatus('Slide tersimpan.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Gagal mengupload slide.'); } }
  if (!session) return <main className="page section"><p className="eyebrow">Owner access</p><h1>Admin studio.</h1><p className="lede">Masuk menggunakan Supabase Auth. Tidak ada credential yang disimpan di source code.</p><form className="form" onSubmit={login}><input type="email" placeholder="Email owner" value={email} onChange={(event) => setEmail(event.target.value)} required /><input type="password" placeholder="Password" value={password} onChange={(event) => setPassword(event.target.value)} required /><button className="button primary">Sign in ↗</button>{status && <p className="status">{status}</p>}</form></main>;
  return <main className="page section"><div className="section-heading"><div><p className="eyebrow">Content studio</p><h1>Owner dashboard.</h1></div><button className="button" onClick={() => void signOutOwner().then(() => setSession(false))}>Log out</button></div>{status && <p className="status">{status}</p>}<section className="grid"><form className="card form" onSubmit={addProject}><span className="tag">New portfolio</span><input name="judul" placeholder="Judul project" required /><input name="slug" placeholder="slug-project" required /><select name="kategori" defaultValue="website"><option value="website">Website</option><option value="aplikasi-web">Aplikasi web</option><option value="company-profile">Company profile</option></select><textarea name="ringkasan" placeholder="Ringkasan" required /><button className="button primary">Simpan portfolio ↗</button></form><article className="card"><span className="tag">Portfolio · {items.length}</span>{items.map((item) => <p key={item.id}><strong>{item.judul}</strong> <button className="tag" onClick={() => void removeProject(item.id)}>Hide</button><br /><small className="muted">{item.kategori}</small></p>)}</article><form className="card form" onSubmit={addTestimonial}><span className="tag">New testimonial</span><input name="nama" placeholder="Nama" required /><input name="jabatan" placeholder="Jabatan" /><textarea name="kutipan" placeholder="Kutipan" required /><button className="button primary">Simpan testimonial ↗</button></form><article className="card"><span className="tag">Testimonials · {testimonials.length}</span>{testimonials.map((item) => <p key={item.id}><strong>{item.nama}</strong><br /><small className="muted">{item.kutipan}</small></p>)}</article><form className="card form" onSubmit={addSlide}><span className="tag">Upload slide</span><input name="judul" placeholder="Judul slide" required /><input name="slug" placeholder="short-slug" pattern="[a-z0-9-]+" required /><input name="file" type="file" accept=".html,.pdf,text/html,application/pdf" required /><small className="muted">HTML/PDF, maksimal 10MB.</small><button className="button primary">Upload slide ↗</button></form><article className="card"><span className="tag">Slides · {slides.length}</span>{slides.map((item) => <p key={item.id}><strong>{item.judul}</strong><br /><small className="muted">/s/{item.slug} · {item.mime_type}</small></p>)}</article><article className="card"><span className="tag">Inbox · {messages.length}</span>{messages.slice(0, 6).map((item) => <p key={item.id}><strong>{item.nama}</strong><br /><small className="muted">{item.email} · {item.status}</small></p>)}</article></section></main>; }
